# Generated by Django 4.1.7 on 2023-05-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discout',
            new_name='discount',
        ),
    ]
